package com.emiraslan.memento.controller;

import com.emiraslan.memento.dto.auth.DevicePublicKeyRegisterRequestDto;
import com.emiraslan.memento.dto.request.BiometricToggleRequestDto;
import com.emiraslan.memento.dto.request.NotificationTokenRegisterRequestDto;
import com.emiraslan.memento.dto.response.UserDeviceResponseDto;
import com.emiraslan.memento.entity.user.User;
import com.emiraslan.memento.service.notification.NotificationTokenService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import com.emiraslan.memento.service.UserDeviceService;

import java.util.List;

@RestController
@RequestMapping("/api/v1/devices")
@RequiredArgsConstructor
@Tag(name = "02 - User Devices")
public class UserDeviceController {

    private final UserDeviceService userDeviceService;
    private final NotificationTokenService notificationTokenService;

    @Operation(
            summary = "Register or update the device's FCM token.",
            description = "Registers the device's FCM token using the Refresh Token. Push notifications are used for Alerts, Medication reminders, General Reminders, and Daily Logs. The aim is to motivate, while not bothering, the users into keeping track of their medication and daily consumptions."
    )
    @PostMapping("/register/fcm-token")
    public ResponseEntity<Void> registerFcmToken(
            @Valid @RequestBody NotificationTokenRegisterRequestDto request
    ) {
        notificationTokenService.upsertNotificationToken(request);
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "Lists a user's own devices.")
    @PreAuthorize("hasAnyAuthority('PATIENT', 'RELATIVE')")
    @GetMapping("/me")
    public ResponseEntity<List<UserDeviceResponseDto>> getMyDevices(
            @AuthenticationPrincipal User currentUser) {

        List<UserDeviceResponseDto> devices = userDeviceService.getUserDevices(currentUser.getUserId());
        return ResponseEntity.ok(devices);
    }

    @Operation(
            summary = "Brings a patient's devices for a relative for remote logout option."
    )
    @PreAuthorize("hasAuthority('RELATIVE') and @guard.canViewPatientData(#patientId, principal)")
    @GetMapping("/related/{patientId}")
    public ResponseEntity<List<UserDeviceResponseDto>> getPatientDevices(
            @PathVariable Integer patientId
    ) {
        List<UserDeviceResponseDto> devices = userDeviceService.getPatientDevices(patientId);
        return ResponseEntity.ok(devices);
    }

    @Operation(
            summary = "Public Key registration for a user's device",
            description = "After the initial login, we save the public key generated by mobile, and the biometric preference of the user."
    )
    @PreAuthorize("hasAnyAuthority('PATIENT', 'RELATIVE') and @guard.isDeviceOwner(#request.deviceId, principal)")
    @PostMapping("/register/public-key")
    public ResponseEntity<Void> registerPublicKey(
            @Valid @RequestBody DevicePublicKeyRegisterRequestDto request
    ) {
        userDeviceService.registerPublicKey(request);
        return ResponseEntity.ok().build();
    }

    @Operation(
            summary = "Toggle biometric login preference for a device",
            description = "Biometric status can only be updated for the current user device (checked by mobile)."
    )
    @PreAuthorize("hasAnyAuthority('PATIENT', 'RELATIVE') and @guard.isDeviceOwner(#deviceId, principal)")
    @PatchMapping("/{deviceId}/biometric")
    public ResponseEntity<Void> toggleBiometric(
            @PathVariable Integer deviceId,
            @NotNull @RequestBody BiometricToggleRequestDto request
    ) {
        userDeviceService.toggleBiometric(deviceId, request.getIsBiometricEnabled());
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "Logout from a device, supports remote logout.")
    @PreAuthorize("hasAuthority('RELATIVE') and @guard.canManageDevice(#deviceId, principal)")
    @DeleteMapping("/logout/{deviceId}")
    public ResponseEntity<Void> logoutDevice(
            @PathVariable Integer deviceId,
            @RequestHeader(value = "Authorization") String authHeader
    ) {

        String jwt = null;
        if (authHeader != null && authHeader.startsWith("Bearer ")) {
            jwt = authHeader.substring(7);
        }

        userDeviceService.logoutDevice(deviceId, jwt);
        return ResponseEntity.ok().build();
    }
}
