# PostgreSQL DB Settings
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# never run data-test.sql file in prod profile
spring.sql.init.mode=never
# Disable Spring Boot Docker Compose feature in production
spring.docker.compose.enabled=false
# Disable api docs and swagger in prod
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Redis Settings (Bucket4j and Cache)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# ===============================
# Security (JWT)
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# Server Settings
# ===============================
server.port=8080
# To obtain the real client IP behind Cloudflare proxy:
server.forward-headers-strategy=framework

# 5 threads for scheduled tasks
spring.task.scheduling.pool.size=5

# Mail Settings
memento.mail.sender=Memento <noreply@emir-memento.me>
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Logging
logging.file.name=/root/memento/memento.log
# Logging starts from INFO level, includes WARN and ERROR
logging.level.root=INFO
logging.level.com.emiraslan.memento=INFO
# A logging file can only be 10 mb max
logging.logback.rollingpolicy.max-file-size=10MB
# Save last 30 days' logs, auto-delete older ones
logging.logback.rollingpolicy.max-history=30
# Log archive total 1 gb max.
logging.logback.rollingpolicy.total-size-cap=1GB