spring.application.name=Memento_Backend

# PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/memento
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driverClassName=org.postgresql.Driver

# jpa creates and drops required db tables on run
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# adds some mock data from data-test.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true

# 5 threads for scheduled tasks
spring.task.scheduling.pool.size=5

# random jwt for testing
jwt.secret=280abf9c42aa9fd41737a546daa38325ef0f8a09c83c7d5e55001dbcdb226fc0

# Redis Settings
spring.data.redis.url=redis://localhost:6379

# Mail Settings
memento.mail.sender=
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true