spring.application.name=Memento_Backend

# H2 database
spring.datasource.url=jdbc:h2:mem:mementodb;MODE=MSSQLServer;IGNORECASE=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# jpa creates and drops required db tables on run
spring.jpa.hibernate.ddl-auto=create-drop

# adds some mock data from data.sql
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.jpa.show-sql=true

# 5 threads for scheduled tasks
spring.task.scheduling.pool.size=5

# JWT for testing if .env doesn't exist
jwt.secret=${JWT_SECRET:280abf9c42aa9fd41737a546daa38325ef0f8a09c83c7d5e55001dbcdb226fc0}

# Redis Settings
spring.data.redis.url=redis://localhost:6379

# Mail Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# your gmail:
spring.mail.username=
# 16 digit app password from your gmail:
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true